services:
  postgresql:
    container_name: postgresql-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - post-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  post:
    container_name: post-service
    build:
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: post-service
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always
    networks:
      - post-service-network

networks:
  post-service-network: 

volumes:
  postgres-volume:
