spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${DB_SERVER:}:${DB_PORT:5432}/${DB_NAME:}
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver  
  config:
    activate:
      on-profile: "dev"
  jpa: 
    show-sql: true
    properties:
      hibernate: 
        show_sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
server:
  port: 8090