spring:
  application:
    name: post-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: "prod"  
  jpa: 
    show-sql: true
    properties:
      hibernate: 
        show_sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
server:
  port: 8090
